name: Stage Kong changes for Prod in a PR

on:
  push:
    branches:
      - main
      - workflow/**
      - feature/**
    paths:
      - platform/kong/.generated/kong.yaml
      - .github/workflows/stage-changes-for-kong-prod.yaml

jobs:
  stage-kong-for-prd:
    name: Stage Kong changes for Prod
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: stage combined file for Prod
        run: cp platform/kong/.generated/kong.yaml PRD/kong/kong.yaml

      - name: deck diff
        id: deck-diff
        # deck diff results in a multi-line output, which requires some
        #  bash gymnastics to handle and pass through to the next job.
        #  See: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-of-a-multiline-string
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "DIFF<<$EOF" >> $GITHUB_ENV
          deck gateway diff --select-tag platform-repo-managed PRD/kong/kong.yaml >> $GITHUB_ENV
          echo "$EOF" >> $GITHUB_ENV

      - name: Create PR to stage changes for the Kong Gateway in production
        uses: peter-evans/create-pull-request@v6
        with:
          title: "❗Prod❗: Staged changes for Kong Gateway prod deployment"
          base: main
          branch: "PRD/kong"
          labels: "PRD,kong"
          body: "Merging this PR will result in the following changes deployed to PRD \n\n ```\n${{env.DIFF}}\n```"

